name: Continuous integration

on:
  push:
    branches: [ master ]

jobs:

  # Build, test and analyze
  build-test-analyze:
    name: Build, test and analyze
    if: "!contains(github.event.head_commit.message, '[skip test]')"
    uses: ./.github/workflows/test.yml
